//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poczta.Sledzenie
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sledzenie.pocztapolska.pl", ConfigurationName="poczta.Sledzenie.SledzeniePortType")]
    public interface SledzeniePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wersja", ReplyAction="urn:wersjaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.wersjaResponse> wersjaAsync(poczta.Sledzenie.wersjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiPl", ReplyAction="urn:sprawdzPrzesylkiPlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiPlResponse> sprawdzPrzesylkiPlAsync(poczta.Sledzenie.sprawdzPrzesylkiPlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkePl", ReplyAction="urn:sprawdzPrzesylkePlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkePlResponse> sprawdzPrzesylkePlAsync(poczta.Sledzenie.sprawdzPrzesylkePlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiOdDo", ReplyAction="urn:sprawdzPrzesylkiOdDoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiOdDoResponse> sprawdzPrzesylkiOdDoAsync(poczta.Sledzenie.sprawdzPrzesylkiOdDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:maksymalnaLiczbaPrzesylek", ReplyAction="urn:maksymalnaLiczbaPrzesylekResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.maksymalnaLiczbaPrzesylekResponse> maksymalnaLiczbaPrzesylekAsync(poczta.Sledzenie.maksymalnaLiczbaPrzesylekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylke", ReplyAction="urn:sprawdzPrzesylkeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkeResponse> sprawdzPrzesylkeAsync(poczta.Sledzenie.sprawdzPrzesylkeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiOdDoPl", ReplyAction="urn:sprawdzPrzesylkiOdDoPlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiOdDoPlResponse> sprawdzPrzesylkiOdDoPlAsync(poczta.Sledzenie.sprawdzPrzesylkiOdDoPlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:witaj", ReplyAction="urn:witajResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.witajResponse> witajAsync(poczta.Sledzenie.witajRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylki", ReplyAction="urn:sprawdzPrzesylkiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiResponse> sprawdzPrzesylkiAsync(poczta.Sledzenie.sprawdzPrzesylkiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wersjaRequest
    {
        
        public wersjaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wersjaResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class wersjaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public wersjaResponse()
        {
        }
        
        public wersjaResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Komunikat
    {
        
        private Przesylka[] przesylkiField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("przesylka")]
        public Przesylka[] przesylki
        {
            get
            {
                return this.przesylkiField;
            }
            set
            {
                this.przesylkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Przesylka
    {
        
        private DanePrzesylki danePrzesylkiField;
        
        private string numerField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public DanePrzesylki danePrzesylki
        {
            get
            {
                return this.danePrzesylkiField;
            }
            set
            {
                this.danePrzesylkiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string numer
        {
            get
            {
                return this.numerField;
            }
            set
            {
                this.numerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class DanePrzesylki
    {
        
        private System.Nullable<System.DateTime> dataNadaniaField;
        
        private bool dataNadaniaFieldSpecified;
        
        private string formatField;
        
        private string kodKrajuNadaniaField;
        
        private string kodKrajuPrzeznField;
        
        private string kodRodzPrzesField;
        
        private string krajNadaniaField;
        
        private string krajPrzeznField;
        
        private System.Nullable<float> masaField;
        
        private bool masaFieldSpecified;
        
        private string numerField;
        
        private Procedura proceduraSerwisField;
        
        private string rodzPrzesField;
        
        private Jednostka urzadNadaniaField;
        
        private Jednostka urzadPrzeznField;
        
        private bool zakonczonoObslugeField;
        
        private bool zakonczonoObslugeFieldSpecified;
        
        private Zdarzenie[] zdarzeniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> dataNadania
        {
            get
            {
                return this.dataNadaniaField;
            }
            set
            {
                this.dataNadaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataNadaniaSpecified
        {
            get
            {
                return this.dataNadaniaFieldSpecified;
            }
            set
            {
                this.dataNadaniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string kodKrajuNadania
        {
            get
            {
                return this.kodKrajuNadaniaField;
            }
            set
            {
                this.kodKrajuNadaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string kodKrajuPrzezn
        {
            get
            {
                return this.kodKrajuPrzeznField;
            }
            set
            {
                this.kodKrajuPrzeznField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string kodRodzPrzes
        {
            get
            {
                return this.kodRodzPrzesField;
            }
            set
            {
                this.kodRodzPrzesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string krajNadania
        {
            get
            {
                return this.krajNadaniaField;
            }
            set
            {
                this.krajNadaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string krajPrzezn
        {
            get
            {
                return this.krajPrzeznField;
            }
            set
            {
                this.krajPrzeznField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<float> masa
        {
            get
            {
                return this.masaField;
            }
            set
            {
                this.masaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool masaSpecified
        {
            get
            {
                return this.masaFieldSpecified;
            }
            set
            {
                this.masaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string numer
        {
            get
            {
                return this.numerField;
            }
            set
            {
                this.numerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public Procedura proceduraSerwis
        {
            get
            {
                return this.proceduraSerwisField;
            }
            set
            {
                this.proceduraSerwisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string rodzPrzes
        {
            get
            {
                return this.rodzPrzesField;
            }
            set
            {
                this.rodzPrzesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public Jednostka urzadNadania
        {
            get
            {
                return this.urzadNadaniaField;
            }
            set
            {
                this.urzadNadaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public Jednostka urzadPrzezn
        {
            get
            {
                return this.urzadPrzeznField;
            }
            set
            {
                this.urzadPrzeznField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool zakonczonoObsluge
        {
            get
            {
                return this.zakonczonoObslugeField;
            }
            set
            {
                this.zakonczonoObslugeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakonczonoObslugeSpecified
        {
            get
            {
                return this.zakonczonoObslugeFieldSpecified;
            }
            set
            {
                this.zakonczonoObslugeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("zdarzenie")]
        public Zdarzenie[] zdarzenia
        {
            get
            {
                return this.zdarzeniaField;
            }
            set
            {
                this.zdarzeniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Procedura
    {
        
        private string kodField;
        
        private string kopertaFirmowaField;
        
        private string nazwaField;
        
        private PrzesylkaPowiazana[] przesylkiPowiazaneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string kopertaFirmowa
        {
            get
            {
                return this.kopertaFirmowaField;
            }
            set
            {
                this.kopertaFirmowaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nazwa
        {
            get
            {
                return this.nazwaField;
            }
            set
            {
                this.nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("przesylkaPowiazana")]
        public PrzesylkaPowiazana[] przesylkiPowiazane
        {
            get
            {
                return this.przesylkiPowiazaneField;
            }
            set
            {
                this.przesylkiPowiazaneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class PrzesylkaPowiazana
    {
        
        private string nrPrzesylkiPowiazanejField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string nrPrzesylkiPowiazanej
        {
            get
            {
                return this.nrPrzesylkiPowiazanejField;
            }
            set
            {
                this.nrPrzesylkiPowiazanejField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Przyczyna
    {
        
        private string kodField;
        
        private string nazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nazwa
        {
            get
            {
                return this.nazwaField;
            }
            set
            {
                this.nazwaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Zdarzenie
    {
        
        private string czasField;
        
        private Jednostka jednostkaField;
        
        private string kodField;
        
        private bool konczaceField;
        
        private bool konczaceFieldSpecified;
        
        private string nazwaField;
        
        private Przyczyna przyczynaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string czas
        {
            get
            {
                return this.czasField;
            }
            set
            {
                this.czasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Jednostka jednostka
        {
            get
            {
                return this.jednostkaField;
            }
            set
            {
                this.jednostkaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool konczace
        {
            get
            {
                return this.konczaceField;
            }
            set
            {
                this.konczaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool konczaceSpecified
        {
            get
            {
                return this.konczaceFieldSpecified;
            }
            set
            {
                this.konczaceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nazwa
        {
            get
            {
                return this.nazwaField;
            }
            set
            {
                this.nazwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public Przyczyna przyczyna
        {
            get
            {
                return this.przyczynaField;
            }
            set
            {
                this.przyczynaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Jednostka
    {
        
        private SzczDaneJednostki daneSzczegoloweField;
        
        private string nazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public SzczDaneJednostki daneSzczegolowe
        {
            get
            {
                return this.daneSzczegoloweField;
            }
            set
            {
                this.daneSzczegoloweField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nazwa
        {
            get
            {
                return this.nazwaField;
            }
            set
            {
                this.nazwaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class SzczDaneJednostki
    {
        
        private float dlGeogrField;
        
        private bool dlGeogrFieldSpecified;
        
        private GodzinyPracy godzinyPracyField;
        
        private string miejscowoscField;
        
        private string nrDomuField;
        
        private string nrLokaluField;
        
        private string pnaField;
        
        private float szerGeogrField;
        
        private bool szerGeogrFieldSpecified;
        
        private string ulicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float dlGeogr
        {
            get
            {
                return this.dlGeogrField;
            }
            set
            {
                this.dlGeogrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dlGeogrSpecified
        {
            get
            {
                return this.dlGeogrFieldSpecified;
            }
            set
            {
                this.dlGeogrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public GodzinyPracy godzinyPracy
        {
            get
            {
                return this.godzinyPracyField;
            }
            set
            {
                this.godzinyPracyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string miejscowosc
        {
            get
            {
                return this.miejscowoscField;
            }
            set
            {
                this.miejscowoscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string nrDomu
        {
            get
            {
                return this.nrDomuField;
            }
            set
            {
                this.nrDomuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nrLokalu
        {
            get
            {
                return this.nrLokaluField;
            }
            set
            {
                this.nrLokaluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pna
        {
            get
            {
                return this.pnaField;
            }
            set
            {
                this.pnaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float szerGeogr
        {
            get
            {
                return this.szerGeogrField;
            }
            set
            {
                this.szerGeogrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool szerGeogrSpecified
        {
            get
            {
                return this.szerGeogrFieldSpecified;
            }
            set
            {
                this.szerGeogrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class GodzinyPracy
    {
        
        private GodzinyZUwagami dniRoboczeField;
        
        private GodzinyZUwagami niedzISwField;
        
        private GodzinyZUwagami sobotyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GodzinyZUwagami dniRobocze
        {
            get
            {
                return this.dniRoboczeField;
            }
            set
            {
                this.dniRoboczeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public GodzinyZUwagami niedzISw
        {
            get
            {
                return this.niedzISwField;
            }
            set
            {
                this.niedzISwField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public GodzinyZUwagami soboty
        {
            get
            {
                return this.sobotyField;
            }
            set
            {
                this.sobotyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class GodzinyZUwagami
    {
        
        private string godzinyField;
        
        private string uwagiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string godziny
        {
            get
            {
                return this.godzinyField;
            }
            set
            {
                this.godzinyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uwagi
        {
            get
            {
                return this.uwagiField;
            }
            set
            {
                this.uwagiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiPl", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiPlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        public sprawdzPrzesylkiPlRequest()
        {
        }
        
        public sprawdzPrzesylkiPlRequest(string[] numer)
        {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiPlResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiPlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public poczta.Sledzenie.Komunikat @return;
        
        public sprawdzPrzesylkiPlResponse()
        {
        }
        
        public sprawdzPrzesylkiPlResponse(poczta.Sledzenie.Komunikat @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkePl", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkePlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numer;
        
        public sprawdzPrzesylkePlRequest()
        {
        }
        
        public sprawdzPrzesylkePlRequest(string numer)
        {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkePlResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkePlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public poczta.Sledzenie.Przesylka @return;
        
        public sprawdzPrzesylkePlResponse()
        {
        }
        
        public sprawdzPrzesylkePlResponse(poczta.Sledzenie.Przesylka @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDo", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string odDnia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doDnia;
        
        public sprawdzPrzesylkiOdDoRequest()
        {
        }
        
        public sprawdzPrzesylkiOdDoRequest(string[] numer, string odDnia, string doDnia)
        {
            this.numer = numer;
            this.odDnia = odDnia;
            this.doDnia = doDnia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDoResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public poczta.Sledzenie.Komunikat @return;
        
        public sprawdzPrzesylkiOdDoResponse()
        {
        }
        
        public sprawdzPrzesylkiOdDoResponse(poczta.Sledzenie.Komunikat @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class maksymalnaLiczbaPrzesylekRequest
    {
        
        public maksymalnaLiczbaPrzesylekRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="maksymalnaLiczbaPrzesylekResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class maksymalnaLiczbaPrzesylekResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        public int @return;
        
        public maksymalnaLiczbaPrzesylekResponse()
        {
        }
        
        public maksymalnaLiczbaPrzesylekResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylke", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numer;
        
        public sprawdzPrzesylkeRequest()
        {
        }
        
        public sprawdzPrzesylkeRequest(string numer)
        {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkeResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public poczta.Sledzenie.Przesylka @return;
        
        public sprawdzPrzesylkeResponse()
        {
        }
        
        public sprawdzPrzesylkeResponse(poczta.Sledzenie.Przesylka @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDoPl", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoPlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string odDnia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doDnia;
        
        public sprawdzPrzesylkiOdDoPlRequest()
        {
        }
        
        public sprawdzPrzesylkiOdDoPlRequest(string[] numer, string odDnia, string doDnia)
        {
            this.numer = numer;
            this.odDnia = odDnia;
            this.doDnia = doDnia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDoPlResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoPlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public poczta.Sledzenie.Komunikat @return;
        
        public sprawdzPrzesylkiOdDoPlResponse()
        {
        }
        
        public sprawdzPrzesylkiOdDoPlResponse(poczta.Sledzenie.Komunikat @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="witaj", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class witajRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imie;
        
        public witajRequest()
        {
        }
        
        public witajRequest(string imie)
        {
            this.imie = imie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="witajResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class witajResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public witajResponse()
        {
        }
        
        public witajResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylki", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        public sprawdzPrzesylkiRequest()
        {
        }
        
        public sprawdzPrzesylkiRequest(string[] numer)
        {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public poczta.Sledzenie.Komunikat @return;
        
        public sprawdzPrzesylkiResponse()
        {
        }
        
        public sprawdzPrzesylkiResponse(poczta.Sledzenie.Komunikat @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SledzeniePortTypeChannel : poczta.Sledzenie.SledzeniePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SledzeniePortTypeClient : System.ServiceModel.ClientBase<poczta.Sledzenie.SledzeniePortType>, poczta.Sledzenie.SledzeniePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SledzeniePortTypeClient() : 
                base(SledzeniePortTypeClient.GetDefaultBinding(), SledzeniePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SledzenieHttpSoap11Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SledzeniePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(SledzeniePortTypeClient.GetBindingForEndpoint(endpointConfiguration), SledzeniePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SledzeniePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SledzeniePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SledzeniePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SledzeniePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SledzeniePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.wersjaResponse> poczta.Sledzenie.SledzeniePortType.wersjaAsync(poczta.Sledzenie.wersjaRequest request)
        {
            return base.Channel.wersjaAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.wersjaResponse> wersjaAsync()
        {
            poczta.Sledzenie.wersjaRequest inValue = new poczta.Sledzenie.wersjaRequest();
            return ((poczta.Sledzenie.SledzeniePortType)(this)).wersjaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiPlResponse> poczta.Sledzenie.SledzeniePortType.sprawdzPrzesylkiPlAsync(poczta.Sledzenie.sprawdzPrzesylkiPlRequest request)
        {
            return base.Channel.sprawdzPrzesylkiPlAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiPlResponse> sprawdzPrzesylkiPlAsync(string[] numer)
        {
            poczta.Sledzenie.sprawdzPrzesylkiPlRequest inValue = new poczta.Sledzenie.sprawdzPrzesylkiPlRequest();
            inValue.numer = numer;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).sprawdzPrzesylkiPlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkePlResponse> poczta.Sledzenie.SledzeniePortType.sprawdzPrzesylkePlAsync(poczta.Sledzenie.sprawdzPrzesylkePlRequest request)
        {
            return base.Channel.sprawdzPrzesylkePlAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkePlResponse> sprawdzPrzesylkePlAsync(string numer)
        {
            poczta.Sledzenie.sprawdzPrzesylkePlRequest inValue = new poczta.Sledzenie.sprawdzPrzesylkePlRequest();
            inValue.numer = numer;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).sprawdzPrzesylkePlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiOdDoResponse> poczta.Sledzenie.SledzeniePortType.sprawdzPrzesylkiOdDoAsync(poczta.Sledzenie.sprawdzPrzesylkiOdDoRequest request)
        {
            return base.Channel.sprawdzPrzesylkiOdDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiOdDoResponse> sprawdzPrzesylkiOdDoAsync(string[] numer, string odDnia, string doDnia)
        {
            poczta.Sledzenie.sprawdzPrzesylkiOdDoRequest inValue = new poczta.Sledzenie.sprawdzPrzesylkiOdDoRequest();
            inValue.numer = numer;
            inValue.odDnia = odDnia;
            inValue.doDnia = doDnia;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).sprawdzPrzesylkiOdDoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.maksymalnaLiczbaPrzesylekResponse> poczta.Sledzenie.SledzeniePortType.maksymalnaLiczbaPrzesylekAsync(poczta.Sledzenie.maksymalnaLiczbaPrzesylekRequest request)
        {
            return base.Channel.maksymalnaLiczbaPrzesylekAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.maksymalnaLiczbaPrzesylekResponse> maksymalnaLiczbaPrzesylekAsync()
        {
            poczta.Sledzenie.maksymalnaLiczbaPrzesylekRequest inValue = new poczta.Sledzenie.maksymalnaLiczbaPrzesylekRequest();
            return ((poczta.Sledzenie.SledzeniePortType)(this)).maksymalnaLiczbaPrzesylekAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkeResponse> poczta.Sledzenie.SledzeniePortType.sprawdzPrzesylkeAsync(poczta.Sledzenie.sprawdzPrzesylkeRequest request)
        {
            return base.Channel.sprawdzPrzesylkeAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkeResponse> sprawdzPrzesylkeAsync(string numer)
        {
            poczta.Sledzenie.sprawdzPrzesylkeRequest inValue = new poczta.Sledzenie.sprawdzPrzesylkeRequest();
            inValue.numer = numer;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).sprawdzPrzesylkeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiOdDoPlResponse> poczta.Sledzenie.SledzeniePortType.sprawdzPrzesylkiOdDoPlAsync(poczta.Sledzenie.sprawdzPrzesylkiOdDoPlRequest request)
        {
            return base.Channel.sprawdzPrzesylkiOdDoPlAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiOdDoPlResponse> sprawdzPrzesylkiOdDoPlAsync(string[] numer, string odDnia, string doDnia)
        {
            poczta.Sledzenie.sprawdzPrzesylkiOdDoPlRequest inValue = new poczta.Sledzenie.sprawdzPrzesylkiOdDoPlRequest();
            inValue.numer = numer;
            inValue.odDnia = odDnia;
            inValue.doDnia = doDnia;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).sprawdzPrzesylkiOdDoPlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.witajResponse> poczta.Sledzenie.SledzeniePortType.witajAsync(poczta.Sledzenie.witajRequest request)
        {
            return base.Channel.witajAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.witajResponse> witajAsync(string imie)
        {
            poczta.Sledzenie.witajRequest inValue = new poczta.Sledzenie.witajRequest();
            inValue.imie = imie;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).witajAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiResponse> poczta.Sledzenie.SledzeniePortType.sprawdzPrzesylkiAsync(poczta.Sledzenie.sprawdzPrzesylkiRequest request)
        {
            return base.Channel.sprawdzPrzesylkiAsync(request);
        }
        
        public System.Threading.Tasks.Task<poczta.Sledzenie.sprawdzPrzesylkiResponse> sprawdzPrzesylkiAsync(string[] numer)
        {
            poczta.Sledzenie.sprawdzPrzesylkiRequest inValue = new poczta.Sledzenie.sprawdzPrzesylkiRequest();
            inValue.numer = numer;
            return ((poczta.Sledzenie.SledzeniePortType)(this)).sprawdzPrzesylkiAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SledzenieHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Transport = new System.ServiceModel.HttpTransportSecurity
                {
                    ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Basic,
                    ProxyCredentialType = System.ServiceModel.HttpProxyCredentialType.None,
                };
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SledzenieHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://tt.poczta-polska.pl/Sledzenie/services/Sledzenie.SledzenieHttpSoap11Endpo" +
                        "int/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SledzeniePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.SledzenieHttpSoap11Endpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SledzeniePortTypeClient.GetEndpointAddress(EndpointConfiguration.SledzenieHttpSoap11Endpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            SledzenieHttpSoap11Endpoint,
        }
    }
}
